(use-modules (xosd bindings))

(let ((osd (xosd-create 1)))
  (xosd-set-timeout! osd 3)
  (xosd-set-pos! osd 'bottom)
  (xosd-set-align! osd 'left)
  (xosd-set-font! osd "-*-dejavu sans-bold-r-normal-*-*-300-*-*-p-*-*-1")
  (xosd-set-colour! osd "gold")
  (xosd-set-shadow-offset! osd 1)
  (xosd-display-string osd 0 "Hello!")
  (xosd-wait-until-no-display osd)
  (xosd-destroy osd))
